// OpenGym Spanish Exercise Names (1324 exercises)
export default {
  "1000": "a una pierna reverse calf raise con banda",
  "1001": "a una pierna split squat con banda",
  "1002": "tumbado/a piernas rectas raise con banda",
  "1003": "sentadilla row con banda",
  "1004": "sentadilla con banda",
  "1005": "de pie crunch con banda",
  "1007": "de pie con giro crunch con banda",
  "1008": "subidas al cajón (step-ups) con banda",
  "1009": "peso muerto piernas rígidas con banda",
  "1010": "piernas rectas deadlift con banda",
  "1011": "sentado/a con giro con banda",
  "1012": "con giro overhead press con banda",
  "1013": "jalón al pecho agarre supino con banda",
  "1014": "abdominales en V (V-ups) con banda",
  "1015": "vertical pallof press con banda",
  "1016": "curl de muñeca con banda",
  "1017": "elevaciones en Y con banda",
  "1018": "encogimientos de hombros con banda",
  "1022": "de pie rear delt row con banda",
  "1023": "straight back stiff leg deadlift con banda",
  "1160": "burpees",
  "1167": "dynamic chest estiramiento",
  "1201": "burpees con mancuernas",
  "1253": "elevación de talones en burro en máquina",
  "1254": "press de banca con banda",
  "1255": "declinado/a pullover con barra",
  "1256": "agarre supino declinado/a en banco press con barra",
  "1257": "agarre supino inclinado/a en banco press con barra",
  "1258": "wide agarre supino en banco press con barra",
  "1259": "behind head chest estiramiento",
  "1260": "declinado/a a una mano press en polea",
  "1261": "declinado/a press en polea",
  "1262": "a una mano declinado/a chest fly en polea",
  "1263": "a una mano fly en fitball en polea",
  "1264": "a una mano inclinado/a fly en fitball en polea",
  "1265": "a una mano inclinado/a press en polea",
  "1266": "a una mano inclinado/a press en fitball en polea",
  "1267": "a una mano press en fitball en polea",
  "1268": "press en fitball en polea",
  "1269": "cruce de poleas para pecho",
  "1270": "upper chest cruce de poleass en polea",
  "1271": "chest and front of shoulder estiramiento",
  "1272": "chest estiramiento with exercise ball en fitball",
  "1273": "clap push up",
  "1274": "deep push up",
  "1275": "drop push up",
  "1276": "declinado/a a una mano fly con mancuernas",
  "1277": "fly en fitball con mancuernas",
  "1278": "aperturas inclinadas en fitball con mancuernas",
  "1279": "inclinado/a a una mano fly con mancuernas",
  "1280": "inclinado/a a una mano fly en fitball con mancuernas",
  "1281": "inclinado/a a una mano press con mancuernas",
  "1282": "inclinado/a a una mano press en fitball con mancuernas",
  "1283": "inclinado/a press en fitball con mancuernas",
  "1284": "tumbado/a pullover en fitball con mancuernas",
  "1285": "a una mano en banco fly con mancuernas",
  "1286": "a una mano chest fly en fitball con mancuernas",
  "1287": "a una mano declinado/a chest press con mancuernas",
  "1288": "a una mano fly en fitball con mancuernas",
  "1289": "a una mano inclinado/a chest press con mancuernas",
  "1290": "a una mano press en fitball con mancuernas",
  "1291": "a una mano pullover en fitball con mancuernas",
  "1292": "a una pierna fly en fitball con mancuernas",
  "1293": "press en fitball con mancuernas",
  "1294": "pull-over hip extension en fitball con mancuernas",
  "1295": "pull-over en fitball con mancuernas",
  "1296": "exercise ball pike push up en fitball",
  "1297": "isometric chest squeeze",
  "1298": "a una mano floor press con pesa rusa",
  "1299": "press de pecho inclinado en máquina",
  "1300": "press de pecho declinado en máquina",
  "1301": "machine inner chest press",
  "1302": "medicine ball chest pass con balón medicinal",
  "1303": "medicine ball chest push from 3 point stance con balón medicinal",
  "1304": "medicine ball chest push multiple response con balón medicinal",
  "1305": "medicine ball chest push single response con balón medicinal",
  "1306": "plyo push up",
  "1307": "flexiones de brazos en bosu ball",
  "1308": "press de banca agarre ancho en máquina Smith",
  "1309": "agarre ancho declinado/a en banco press en máquina Smith",
  "1310": "drop push up con lastre",
  "1311": "wide hand push up",
  "1312": "medicine ball chest push with run release con balón medicinal",
  "1313": "unilateral row en máquina",
  "1314": "hiperextensiones lumbares en fitball",
  "1316": "bent arm pullover con barra",
  "1317": "agarre supino inclinado/a en banco row con barra",
  "1318": "inclinado/a en banco row en polea",
  "1319": "palm rotational row en polea",
  "1320": "rope cruce de poleas sentado/a row en polea",
  "1321": "rope elevated sentado/a row en polea",
  "1322": "rope extension inclinado/a en banco row en polea",
  "1323": "rope sentado/a row en polea",
  "1324": "upper row en polea",
  "1325": "agarre ancho rear pulldown trasnuca en polea",
  "1326": "dominadas supinas",
  "1327": "agarre estrecho chin-up",
  "1328": "tumbado/a rear delt row con mancuernas",
  "1329": "palm rotational remo inclinado con mancuernas",
  "1330": "agarre supino inclinado/a en banco a una mano row con mancuernas",
  "1331": "agarre supino inclinado/a en banco two arm row con mancuernas",
  "1332": "exercise ball alterno/a arm ups en fitball",
  "1333": "exercise ball back extension with arms extended en fitball",
  "1334": "exercise ball back extension with hands behind head en fitball",
  "1335": "exercise ball back extension with knees off ground en fitball",
  "1336": "exercise ball back extension with con rotación en fitball",
  "1338": "exercise ball hug en fitball",
  "1339": "exercise ball lat estiramiento en fitball",
  "1341": "exercise ball lower back estiramiento (pyramid) en fitball",
  "1342": "exercise ball tumbado/a side lat estiramiento en fitball",
  "1343": "exercise ball prono leg raise en fitball",
  "1344": "agarre supino remo inclinado con barra EZ",
  "1345": "two arm row con pesa rusa",
  "1346": "de rodillas lat estiramiento",
  "1347": "a una mano lateral wide pulldown en máquina",
  "1348": "agarre supino vertical row en máquina",
  "1349": "reverse t-bar row en máquina",
  "1350": "remo sentado en máquina",
  "1351": "t-bar agarre supino row en máquina",
  "1352": "lower back curl",
  "1353": "medicine ball catch and overhead throw con balón medicinal",
  "1354": "medicine ball overhead slam con balón medicinal",
  "1355": "a una mano against wall",
  "1356": "a una mano lateral high row en máquina",
  "1358": "side tumbado/a floor estiramiento",
  "1359": "remo inclinado en máquina Smith",
  "1360": "remo a una mano en máquina Smith",
  "1361": "agarre supino remo inclinado en máquina Smith",
  "1362": "sphinx",
  "1363": "spine estiramiento",
  "1364": "de pie pelvic tilt",
  "1365": "upper back estiramiento",
  "1366": "upward facing dog",
  "1367": "agarre ancho rear pull-up",
  "1368": "círculos con tobillos",
  "1369": "two legs calf raise - (band under both legs) v. 2 con banda",
  "1370": "floor calf raise con barra",
  "1371": "elevación de talones sentado con barra",
  "1372": "elevación de talones de pie",
  "1373": "elevación de talones de pie",
  "1374": "saltos al cajón (box jumps) down with a una pierna stabilization",
  "1375": "elevación de talones de pie en polea",
  "1376": "de pie a una pierna calf raise en polea",
  "1377": "calf estiramiento with hands against wall",
  "1378": "calf estiramiento with rope",
  "1379": "elevación de talones sentado con mancuernas",
  "1380": "sentado/a a una pierna calf raise - hammer grip con mancuernas",
  "1381": "sentado/a a una pierna calf raise - palm up con mancuernas",
  "1382": "exercise ball on the wall calf raise en fitball",
  "1383": "hack calf raise",
  "1384": "hack a una pierna calf raise",
  "1385": "sentado/a squat calf raise on leg press machine en máquina",
  "1386": "a una pierna donkey calf raise",
  "1387": "a una pierna floor calf raise",
  "1388": "peroneals estiramiento",
  "1389": "posterior tibialis estiramiento",
  "1390": "sentado/a calf estiramiento",
  "1391": "sled calf press on leg press",
  "1392": "sled a una pierna calf press on leg press",
  "1393": "a una pierna floor calf raise en máquina Smith",
  "1394": "reverse calf raises en máquina Smith",
  "1395": "sentado/a a una pierna calf raise en máquina Smith",
  "1396": "toe raise en máquina Smith",
  "1397": "de pie calves",
  "1398": "de pie calves calf estiramiento",
  "1399": "en banco dip en suelo",
  "1401": "muscle-up (on vertical bar)",
  "1403": "neck side estiramiento",
  "1405": "estiramiento de pectorales y espalda",
  "1407": "calf push estiramiento with hands against wall",
  "1408": "hip lift con banda",
  "1409": "puente de glúteos con barra",
  "1410": "zancadas laterales con barra",
  "1411": "palms down wrist curl over a en banco con barra",
  "1412": "palms up wrist curl over a en banco con barra",
  "1413": "reverse a una mano curl en polea",
  "1414": "a una mano reverse preacher curl con mancuernas",
  "1415": "a una mano sentado/a neutral wrist curl con mancuernas",
  "1416": "exercise ball a una pierna prono lower body con rotación en fitball",
  "1417": "exercise ball one legged diagonal kick curl femoral en fitball",
  "1418": "hug keens to chest",
  "1419": "iron cross estiramiento",
  "1420": "de rodillas jump squat",
  "1421": "modified push up to lower arms",
  "1422": "pelvic tilt into bridge",
  "1423": "reverse hyper on flat en banco",
  "1424": "sentado/a glute estiramiento",
  "1425": "sled 45 degrees a una pierna press",
  "1426": "sentado/a wrist curl en máquina Smith",
  "1427": "piernas rectas outer hip abductor",
  "1428": "wrist circles",
  "1429": "agarre ancho pull-up",
  "1430": "fondos de pecho (on dip-pull-up cage)",
  "1431": "dominadas supinas asistidas en máquina",
  "1432": "dominadas asistidas en máquina",
  "1433": "sentadilla frontal (clean grip) en máquina Smith",
  "1434": "low bar squat en máquina Smith",
  "1435": "low bar squat con barra",
  "1436": "high bar squat con barra",
  "1437": "finger curls con mancuernas",
  "1438": "sentado/a two arm military press con pesa rusa",
  "1439": "gripless shrug v. 2 en máquina",
  "1441": "over en banco a una mano reverse wrist curl con mancuernas",
  "1451": "sentado/a dip en máquina",
  "1452": "sentado/a crunch en máquina",
  "1456": "de pie agarre estrecho military press con barra",
  "1457": "de pie wide military press con barra",
  "1458": "sentado/a curls con barra EZ",
  "1459": "peso muerto rumano con mancuernas",
  "1460": "zancadas caminando",
  "1461": "sentadilla trasera (back pov) con barra",
  "1462": "sentadilla trasera (side pov) con barra",
  "1463": "sled 45° leg press (side pov)",
  "1464": "sled 45в° leg press (back pov)",
  "1466": "con giro hip lift",
  "1467": "flexiones de brazos on lower arms",
  "1468": "crab con giro toe touch",
  "1471": "inchworm",
  "1472": "forward jump",
  "1473": "salto hacia atrás",
  "1476": "a una pierna squat",
  "1479": "press de pecho inclinado v. 2 en máquina",
  "1489": "sentadilla sissy",
  "1490": "elevación de talones de pie (on a staircase)",
  "1494": "butterfly yoga pose",
  "1495": "oblique crunch v. 2",
  "1496": "sledge hammer",
  "1511": "hamstring estiramiento",
  "1512": "estiramiento de cuádriceps en cuadrupedia",
  "1545": "full zercher squat con barra",
  "1548": "chair leg extended estiramiento",
  "1559": "exercise ball hip flexor estiramiento en fitball",
  "1560": "exercise ball sentado/a hamstring estiramiento en fitball",
  "1564": "intermediate hip flexor and quad estiramiento",
  "1576": "leg up hamstring estiramiento",
  "1582": "reclining big toe pose with rope",
  "1585": "runners estiramiento",
  "1587": "sentado/a wide angle pose sequence",
  "1599": "de pie hamstring and calf estiramiento with strap",
  "1604": "world greatest estiramiento",
  "1614": "curl predicador v. 2 en máquina",
  "1615": "hammer grip preacher curl en máquina",
  "1616": "agarre supino preacher curl en máquina",
  "1617": "declinado/a a una mano hammer press con mancuernas",
  "1618": "inclinado/a hammer press en fitball con mancuernas",
  "1619": "inclinado/a a una mano hammer press con mancuernas",
  "1620": "inclinado/a a una mano hammer press en fitball con mancuernas",
  "1621": "a una mano hammer press en fitball con mancuernas",
  "1622": "a una mano agarre supino press con mancuernas",
  "1623": "palms in inclinado/a en banco press con mancuernas",
  "1624": "reverse en banco press con mancuernas",
  "1625": "machine declinado/a agarre estrecho en banco press en máquina Smith",
  "1626": "machine reverse declinado/a agarre estrecho en banco press en máquina Smith",
  "1627": "agarre estrecho preacher curl con barra EZ",
  "1628": "curl araña con barra EZ",
  "1629": "de pie agarre ancho curl de bíceps con barra",
  "1630": "agarre estrecho curl en polea",
  "1631": "curl concentrado en polea",
  "1632": "drag curl en polea",
  "1633": "a una mano preacher curl en polea",
  "1634": "tumbado/a bicep curl en polea",
  "1635": "a una mano reverse preacher curl en polea",
  "1636": "overhead curl en polea",
  "1637": "overhead curl en fitball en polea",
  "1638": "jalón dorsal bicep curl en polea",
  "1639": "rope hammer preacher curl en polea",
  "1640": "rope a una mano hammer preacher curl en polea",
  "1641": "sentado/a curl en polea",
  "1642": "sentado/a a una mano concentration curl en polea",
  "1643": "sentado/a overhead curl en polea",
  "1644": "sentadillating curl en polea",
  "1645": "two arm curl on inclinado/a en banco en polea",
  "1646": "alterno/a hammer preacher curl con mancuernas",
  "1647": "alterno/a preacher curl con mancuernas",
  "1648": "alterno/a sentado/a hammer curl con mancuernas",
  "1649": "alterno/a bicep curl with leg raised en fitball con mancuernas",
  "1650": "alterno/a sentado/a bicep curl en fitball con mancuernas",
  "1651": "curl de bíceps lunge with bowling motion con mancuernas",
  "1652": "curl de bíceps en fitball with leg raised con mancuernas",
  "1653": "curl de bíceps with stork stance con mancuernas",
  "1654": "curl de bíceps reverse con mancuernas",
  "1655": "curl de bíceps squat con mancuernas",
  "1656": "curl de bíceps v sit en bosu ball con mancuernas",
  "1657": "cross body hammer curl v. 2 con mancuernas",
  "1658": "zancadas with bicep curl con mancuernas",
  "1659": "curl martillo en fitball con mancuernas",
  "1660": "de rodillas bicep curl exercise ball con mancuernas",
  "1661": "tumbado/a supino curl de bíceps con mancuernas",
  "1662": "tumbado/a wide curl con mancuernas",
  "1663": "a una mano hammer preacher curl con mancuernas",
  "1664": "high curl con mancuernas",
  "1665": "a una mano prono curl con mancuernas",
  "1666": "a una mano prono hammer curl con mancuernas",
  "1667": "a una mano reverse spider curl con mancuernas",
  "1668": "a una mano sentado/a bicep curl en fitball con mancuernas",
  "1669": "a una mano sentado/a hammer curl con mancuernas",
  "1670": "a una mano de pie curl con mancuernas",
  "1671": "a una mano de pie hammer curl con mancuernas",
  "1672": "a una mano zottman preacher curl con mancuernas",
  "1673": "curl predicador over exercise ball con mancuernas",
  "1674": "prono inclinado/a hammer curl con mancuernas",
  "1675": "reverse spider curl con mancuernas",
  "1676": "sentado/a alterno/a hammer curl en fitball con mancuernas",
  "1677": "sentado/a bicep curl con mancuernas",
  "1678": "sentado/a hammer curl con mancuernas",
  "1679": "sentado/a a una mano bicep curl en fitball with leg raised con mancuernas",
  "1680": "de pie a una mano curl over inclinado/a en banco con mancuernas",
  "1682": "sentado/a agarre estrecho concentration curl con barra EZ",
  "1683": "machine bicep curl en máquina Smith",
  "1684": "subidas al cajón (step-ups) a una pierna balance with bicep curl con mancuernas",
  "1685": "sentadilla to overhead reach",
  "1686": "sentadilla to overhead reach with con giro",
  "1687": "posterior step to overhead reach",
  "1688": "zancadas with con giro",
  "1689": "push and pull bodyweight",
  "1700": "push press con mancuernas",
  "1701": "medicine ball agarre estrecho push up con balón medicinal",
  "1705": "sentadilla en bosu ball",
  "1707": "prono con giro en fitball",
  "1708": "estiramiento de gemelos tumbado asistido",
  "1709": "estiramiento de glúteos tumbado asistido",
  "1710": "estiramiento de glúteo y piramidal asistido",
  "1712": "estiramiento de aductores de lado asistido",
  "1713": "estiramiento de cuádriceps prono asistido",
  "1714": "estiramiento de recto femoral prono asistido",
  "1716": "estiramiento de pectoral mayor en fitball asistido",
  "1717": "sentadilla row (with rope attachment) en polea",
  "1718": "sentado/a agarre estrecho trasnuca extensión de tríceps con barra",
  "1719": "inclinado/a agarre estrecho en banco press con barra",
  "1720": "tumbado/a back of the head tricep extension con barra",
  "1721": "agarre supino press francés (skullcrusher) con barra",
  "1722": "high pulley overhead tricep extension en polea",
  "1723": "a una mano tricep pushdown en polea",
  "1724": "rope high pulley overhead tricep extension en polea",
  "1725": "rope inclinado/a tricep extension en polea",
  "1726": "rope tumbado/a en suelo tricep extension en polea",
  "1727": "de pie agarre supino a una mano overhead tricep extension en polea",
  "1728": "two arm tricep kickback en polea",
  "1729": "tumbado/a alterno/a extension con mancuernas",
  "1730": "sentado/a bent over alterno/a kickback con mancuernas",
  "1731": "agarre estrecho press con mancuernas",
  "1732": "forward lunge extensión de tríceps con mancuernas",
  "1733": "inclinado/a two arm extension con mancuernas",
  "1734": "kickbacks en fitball con mancuernas",
  "1735": "tumbado/a single extension con mancuernas",
  "1736": "a una mano french press en fitball con mancuernas",
  "1737": "sentado/a bent over extensión de tríceps con mancuernas",
  "1738": "sentado/a agarre supino a una mano overhead tricep extension con mancuernas",
  "1739": "de pie alterno/a tricep kickback con mancuernas",
  "1740": "de pie bent over a una mano extensión de tríceps con mancuernas",
  "1741": "de pie bent over two arm extensión de tríceps con mancuernas",
  "1742": "patada de tríceps with stork stance con mancuernas",
  "1743": "con giro en banco press con mancuernas",
  "1744": "exercise ball dip en fitball",
  "1745": "exercise ball sentado/a triceps estiramiento en fitball",
  "1746": "exercise ball supino extensión de tríceps en fitball",
  "1747": "french press en fitball con barra EZ",
  "1748": "tumbado/a agarre estrecho extensión de tríceps behind head con barra EZ",
  "1749": "de pie french press con barra EZ",
  "1750": "medicine ball supino chest throw con balón medicinal",
  "1751": "pin presses con barra",
  "1752": "machine inclinado/a tricep extension en máquina Smith",
  "1753": "three en banco dip",
  "1754": "three en banco dips con lastre",
  "1755": "fondos de trícepss con lastre",
  "1756": "a una pierna deadlift con barra",
  "1757": "a una pierna deadlift con mancuernas",
  "1758": "abdominales sit-up asistidos",
  "1759": "a una pierna squat (pistol) male",
  "1760": "sentadilla goblet con mancuernas",
  "1761": "colgado/a oblique knee raise",
  "1763": "shoulder grip pull-up",
  "1764": "colgado/a leg hip raise",
  "1765": "remo al mentón (back pov) con mancuernas",
  "1766": "self assisted inverse leg curl",
  "1767": "fondos de tríceps on high parallel bars con lastre",
  "1769": "side tumbado/a curl de bíceps",
  "1770": "biceps leg concentration curl",
  "1771": "de rodillas extensión de tríceps",
  "1772": "elbow lift - reverse push-up",
  "1773": "a una mano towel row",
  "1774": "side bridge hip abduction",
  "1775": "plancha lateral hip adduction",
  "2133": "paseo del granjero (farmer walk)",
  "2135": "front plank con lastre",
  "2136": "cuban press v. 2 con mancuernas",
  "2137": "press Arnold con mancuernas",
  "2138": "stationary bike run v. 3",
  "2139": "hands bike",
  "2141": "walk elliptical cross trainer",
  "2142": "ski ergometer",
  "2143": "de pie around world con mancuernas",
  "2144": "sentado/a chest press en polea",
  "2186": "declinado/a extensión de tríceps con barra EZ",
  "2187": "reverse agarre estrecho en banco press con barra",
  "2188": "sentado/a extensión de tríceps con mancuernas",
  "2189": "dumbbells sentado/a extensión de tríceps",
  "2202": "hip estiramiento con rodillo",
  "2203": "sentado/a shoulder flexor depresor retractor con rodillo",
  "2204": "body saw con rodillo",
  "2205": "hip lat estiramiento con rodillo",
  "2206": "crunch invertido con rodillo",
  "2207": "side lat estiramiento con rodillo",
  "2208": "back estiramiento con rodillo",
  "2209": "sentado/a a una pierna shoulder flexor depresor retractor con rodillo",
  "2271": "left hook. boxing",
  "2285": "pull-over en máquina",
  "2286": "extensión de cadera v. 2 en máquina",
  "2287": "alterno/a leg press en máquina",
  "2288": "gripper hands en máquina",
  "2289": "calf press en máquina",
  "2292": "rear delt raise con mancuernas",
  "2293": "de pie zottman preacher curl con mancuernas",
  "2294": "zottman preacher curl con mancuernas",
  "2297": "stability ball crunch (full range hands behind head) en fitball",
  "2298": "remo invertido (australiano) en banco",
  "2300": "remo invertido (australiano) rodillas flexionadas",
  "2311": "walking on stepmill",
  "2312": "tumbado/a elbow to knee",
  "2315": "rotary calf en máquina",
  "2317": "sentado/a bent arm lateral raise con mancuernas",
  "2318": "press de hombros v. 3 en máquina",
  "2321": "de pie inner curl de bíceps v. 2 con mancuernas",
  "2327": "agarre supino row con mancuernas",
  "2328": "narrow push-up en fitball",
  "2329": "spine con giro",
  "2330": "jalón al pecho en polea",
  "2331": "cycle cross trainer",
  "2333": "elevación de piernas rectas colgado en barra",
  "2334": "sled tumbado/a calf press",
  "2335": "sentado/a calf press en máquina",
  "2355": "elevación de rodillas colgado en barra",
  "2363": "agarre ancho chest dip on high parallel bars",
  "2364": "fondos de pecho agarre ancho asistidos en máquina",
  "2368": "sentadilla divididas",
  "2371": "giros rusos v. 2 con lastre",
  "2397": "scott press con mancuernas",
  "2398": "agarre estrecho push-up (on knees)",
  "2399": "sentado/a con giro en polea",
  "2400": "inverse leg curl (on pull-up cable machine)",
  "2401": "curl de bíceps (with arm blaster) con mancuernas",
  "2402": "curl martillos (with arm blaster) con mancuernas",
  "2403": "alterno/a curl de bíceps (with arm blaster) con mancuernas",
  "2404": "ez-bar curl de bíceps (with arm blaster)",
  "2405": "jalón de tríceps en polea (v-bar) (with arm blaster)",
  "2406": "agarre supino jalón de tríceps en polea (sz-bar) (with arm blaster)",
  "2407": "curl de bíceps (with arm blaster) con barra",
  "2414": "de pie concentration curl con barra",
  "2429": "frog crunch",
  "2432": "ez-bar agarre estrecho en banco press",
  "2459": "tire flip",
  "2462": "fondos de pecho on straight bar",
  "2464": "thibaudeau kayak row en polea",
  "2466": "bridge - mountain climber (cross body)",
  "2470": "tumbado/a en suelo rear delt raise con mancuernas",
  "2567": "sentado/a piriformis estiramiento",
  "2571": "rocking frog estiramiento",
  "2611": "horizontal a una pierna press en máquina",
  "2612": "salto con cuerda",
  "2616": "lateral pulldown with v-bar en polea",
  "2705": "tumbado/a pronation en suelo con mancuernas",
  "2706": "tumbado/a supination en suelo con mancuernas",
  "2736": "agarre supino lateral pulldown en máquina",
  "2741": "ez-barbell de pie agarre ancho curl de bíceps",
  "2796": "subidas al cajón (step-ups) lunge con mancuernas",
  "2798": "sentadilla jump step rear lunge con barra",
  "2799": "sitted alterno/a leg raise con barra",
  "2800": "sitted alterno/a leg raise con barra",
  "2801": "twisted leg raise",
  "2802": "twisted leg raise",
  "2803": "supported squat con mancuernas",
  "2805": "a una pierna deadlift with stepbox support con mancuernas",
  "2808": "sumo pull through con mancuernas",
  "2810": "sentadilla dividida v. 2 con barra",
  "2812": "subidas al cajón (step-ups) split squat con mancuernas",
  "2963": "captains chair piernas rectas raise",
  "2987": "agarre estrecho chin-up on dip cage con lastre",
  "3006": "resistance band sentado/a hip abduction con banda",
  "3007": "resistance band leg extension con banda",
  "3010": "tumbado/a bent arms pullover con barra EZ",
  "3011": "inclinado/a scapula push up",
  "3012": "scapula dips",
  "3013": "low glute bridge en suelo",
  "3016": "curl-up",
  "3017": "remo Pendlay con barra",
  "3019": "en banco pull-ups",
  "3021": "scapula push-up",
  "3116": "jalón dorsal agarre supino con banda",
  "3117": "jalón dorsal agarre estrecho con banda",
  "3119": "potty squat",
  "3122": "resistance band sentado/a shoulder press con banda",
  "3123": "resistance band sentado/a curl de bíceps con banda",
  "3124": "resistance band sentado/a chest press con banda",
  "3132": "potty squat with support",
  "3142": "sentadilla sumo en máquina Smith",
  "3144": "resistance band sentado/a straight back row con banda",
  "3145": "flexiones de brazos plus",
  "3147": "pelvic tilt",
  "3156": "de pie agarre estrecho a una mano row",
  "3158": "de pie agarre estrecho row",
  "3161": "de pie a una mano row con toalla",
  "3162": "de pie a una mano row",
  "3165": "de pie row con toalla",
  "3166": "de pie row",
  "3167": "sentadillating row con toalla",
  "3168": "sentadillating row",
  "3193": "glute-ham raise",
  "3194": "frankenstein squat",
  "3195": "tumbado/a two-a una pierna curl en máquina",
  "3200": "remo inclinado with v-bar en máquina",
  "3201": "quarter sit-up",
  "3202": "half sit-up",
  "3203": "prisoner half sit-up",
  "3204": "abdominales completos con brazos sobre la cabeza",
  "3211": "de rodillas push-up",
  "3212": "basic toe touch",
  "3213": "side-to-side toe touch",
  "3214": "toque circular de pies con brazos abiertos",
  "3215": "hands reversed clasped circular toe touch",
  "3216": "chest tap push-up",
  "3217": "modified hindu push-up",
  "3218": "hands clasped circular toe touch",
  "3219": "scissor jumps",
  "3220": "saltos con apertura de piernas",
  "3221": "half knee bends",
  "3222": "semi squat jump",
  "3223": "star jump",
  "3224": "jack jump",
  "3231": "two toe touch",
  "3234": "hyght dumbbell fly",
  "3235": "assisted inverse leg curl en polea",
  "3236": "resistance band hip thrusts on knees con banda",
  "3237": "landmine lateral raise",
  "3239": "de rodillas plank tap shoulder",
  "3240": "exercise ball on the wall calf raise (tennis ball between knees) en fitball",
  "3241": "exercise ball on the wall calf raise (tennis ball between ankles) en fitball",
  "3281": "sentadilla trasera en máquina Smith",
  "3286": "muscle up con lastre",
  "3287": "elbow dips",
  "3288": "korean dips",
  "3289": "impossible dips",
  "3290": "one hand pull up con lastre",
  "3291": "stalder press",
  "3292": "elevator",
  "3293": "dominada de arquero",
  "3294": "flexión de arquero",
  "3295": "front lever reps",
  "3296": "front lever",
  "3297": "back lever en barra",
  "3298": "straddle planche",
  "3299": "full planche",
  "3300": "lean planche",
  "3301": "frog planche",
  "3302": "handstand",
  "3303": "flag",
  "3304": "skin the cat",
  "3305": "thruster con barra",
  "3312": "muscle up (on bar) con lastre",
  "3313": "straight bar dip con lastre",
  "3314": "straddle maltese",
  "3315": "full maltese",
  "3318": "swing con pesa rusa 360",
  "3327": "full planche push-up",
  "3360": "bear crawl",
  "3361": "skater hops",
  "3418": "l-pull-up",
  "3419": "l-sit en suelo",
  "3420": "v-sit en suelo",
  "3433": "swimmer kicks v. 2",
  "3470": "forward lunge",
  "3523": "puente de glúteos two legs en banco",
  "3533": "quads",
  "3541": "inclinado/a y-raise con mancuernas",
  "3542": "inclinado/a t-raise con mancuernas",
  "3543": "drop jump squat",
  "3544": "inclinado/a side plank",
  "3545": "inclinado/a alterno/a press con mancuernas",
  "3546": "sentado/a alterno/a shoulder con mancuernas",
  "3547": "sentado/a curl de bíceps to shoulder press con mancuernas",
  "3548": "a una mano overhead carry con mancuernas",
  "3552": "quick feet v. 2",
  "3560": "de pie alterno/a hammer curl and press con mancuernas",
  "3561": "puente de glúteos march",
  "3562": "puente de glúteos two legs en banco con barra",
  "3563": "a una mano pulldown en polea",
  "3582": "zancadas with jump",
  "3635": "contralateral forward lunge con mancuernas",
  "3636": "high knee against wall",
  "3637": "run",
  "3638": "push to run",
  "3639": "rodillas flexionadas tumbado/a con giro",
  "3640": "knee touch crunch",
  "3641": "de rodillas step with swing con pesa rusa con lastre",
  "3642": "estiramiento lunge con lastre",
  "3643": "cossack squats con lastre",
  "3644": "zancadas with swing con lastre",
  "3645": "a una pierna bridge with outestiramientoed leg",
  "3655": "walking high knees lunge",
  "3656": "short stride run",
  "3662": "pike-to-cobra push-up",
  "3663": "reverse plank with leg lift",
  "3664": "plancha lateral with rear fly con mancuernas",
  "3665": "power point plank",
  "3666": "walking on inclinado/a treadmill",
  "3667": "side tumbado/a hip adduction",
  "3669": "de pie archer",
  "3670": "declinado/a sit-up con lastre",
  "3671": "ski step",
  "3672": "pasos adelante y atrás en tijera",
  "3679": "abdominales sit-up with arms on chest",
  "3697": "de rodillas rear delt row (with rope) en polea",
  "3698": "inchworm v. 2",
  "3699": "shoulder tap",
  "3758": "de pie chest press en máquina",
  "3759": "sentado/a good morning en máquina",
  "3760": "sentado/a crunch v. 2 en máquina",
  "3769": "curtsey squat",
  "3785": "inclinado/a push-up (on box)",
  "3888": "a una mano snatch con mancuernas",
  "5201": "waiter curl de bíceps con mancuernas",
  "0001": "abdominales 3/4 (sit-up)",
  "0002": "flexión lateral de tronco a 45°",
  "0003": "bicicleta abdominal (air bike)",
  "0006": "toques alternos de talón",
  "0007": "jalón lateral alterno en polea",
  "0009": "fondos de pecho asistidos en máquina",
  "0011": "elevación de rodillas colgado asistida",
  "0010": "elevación de rodillas colgado con bajada explosiva",
  "0012": "elevación de piernas tumbado con empuje lateral",
  "0013": "elevación de piernas tumbado con bajada asistida",
  "0014": "giros rusos con balón medicinal asistido",
  "0015": "dominadas agarre estrecho neutro asistidas en máquina",
  "0016": "curl femoral tumbado asistido",
  "0017": "dominadas asistidas en máquina",
  "0018": "extensión de tríceps sobre la cabeza con toalla asistida",
  "0019": "fondos de tríceps asistidos en máquina",
  "0020": "equilibrio sobre tabla basculante",
  "0968": "alterno/a curl de bíceps con banda",
  "0969": "alterno/a v-up con banda",
  "0970": "assisted pull-up con banda",
  "0971": "assisted wheel rollerout con banda",
  "0980": "bent-over hip extension con banda",
  "0972": "crunch en bicicleta con banda",
  "0974": "jalón al pecho agarre cerrado con banda",
  "0975": "agarre estrecho push-up con banda",
  "0976": "curl concentrado con banda",
  "0977": "front lateral raise con banda",
  "0978": "elevaciones frontales con banda",
  "0979": "horizontal pallof press con banda",
  "0981": "jack knife sit-up con banda",
  "0983": "de rodillas a una mano pulldown con banda",
  "0985": "de rodillas con giro crunch con banda",
  "0984": "tumbado/a hip internal con rotación con banda",
  "0986": "a una mano overhead curl de bíceps con banda",
  "0987": "a una mano a una pierna split squat con banda",
  "0988": "a una mano de pie low row con banda",
  "0989": "a una mano con giro chest press con banda",
  "0990": "a una mano con giro sentado/a row con banda",
  "0991": "pull-through para glúteos con banda",
  "0992": "push sit-up con banda",
  "0993": "pájaros (deltoides posterior) con banda",
  "0994": "curl invertido de muñeca con banda",
  "0996": "sentado/a hip internal con rotación con banda",
  "0997": "press de hombros con banda",
  "0998": "side extensión de tríceps con banda",
  "0999": "a una pierna calf raise con banda",
  "0023": "alterno/a curl de bíceps con barra",
  "0024": "en banco front squat con barra",
  "0025": "press de banca con barra",
  "0026": "en banco squat con barra",
  "0027": "remo inclinado con barra",
  "0028": "cargada (clean) and press con barra",
  "0029": "cargada (clean)-grip front squat con barra",
  "0030": "press de banca agarre estrecho con barra",
  "0031": "curl de bíceps con barra",
  "0032": "peso muerto con barra",
  "0033": "press de banca declinado con barra",
  "0034": "declinado/a bent arm pullover con barra",
  "0035": "declinado/a agarre estrecho to skull press con barra",
  "0036": "declinado/a agarre ancho press con barra",
  "0037": "declinado/a agarre ancho pullover con barra",
  "0038": "drag curl con barra",
  "0039": "front chest squat con barra",
  "0041": "remo al mentón con barra",
  "0040": "elevaciones frontales and pullover con barra",
  "0042": "sentadilla frontal con barra",
  "0043": "sentadilla trasera con barra",
  "0044": "buenos días con barra",
  "0045": "guillotine en banco press con barra",
  "0046": "sentadilla hack con barra",
  "0047": "press de banca inclinado con barra",
  "0048": "inclinado/a reverse-grip press con barra",
  "0049": "remo inclinado con barra",
  "0050": "inclinado/a shoulder raise con barra",
  "0051": "jefferson squat con barra",
  "0052": "jm en banco press con barra",
  "0053": "buenos días con barra",
  "0054": "zancadas con barra",
  "0055": "tumbado/a agarre estrecho press con barra",
  "0056": "tumbado/a agarre estrecho extensión de tríceps con barra",
  "0057": "tumbado/a extension con barra",
  "0058": "tumbado/a lifting (on hip) con barra",
  "0059": "tumbado/a preacher curl con barra",
  "0061": "extensión de tríceps tumbado con barra",
  "0060": "press francés con barra (skullcrusher)",
  "0063": "elevación de rodillas colgado",
  "0064": "elevación de piernas rectas colgado",
  "0065": "a una mano floor press con barra",
  "0066": "a una mano side deadlift con barra",
  "0067": "a una mano snatch con barra",
  "0068": "a una pierna squat con barra",
  "0069": "sentadilla sobre la cabeza con barra",
  "0070": "curl predicador con barra",
  "0071": "press sit-up con barra",
  "0072": "prono inclinado/a curl con barra",
  "0073": "fondos en paralelas para tríceps",
  "0022": "pull-over to press con barra",
  "0074": "flexiones de brazos",
  "0075": "flexiones diamante",
  "0076": "fondos de tríceps entre bancos",
  "0078": "rear lunge con barra",
  "0077": "rear lunge v. 2 con barra",
  "0079": "revers wrist curl v. 2 con barra",
  "0080": "curl invertido con barra",
  "0118": "agarre supino remo inclinado con barra",
  "0081": "curl de bíceps sentado con barra",
  "0082": "curl invertido de muñeca con barra",
  "0084": "rollerout con barra",
  "0083": "rollerout from en banco con barra",
  "0085": "peso muerto rumano con barra",
  "0086": "sentado/a behind head military press con barra",
  "0087": "sentado/a bradford rocky press con barra",
  "0088": "elevación de talones sentado con barra",
  "0089": "sentado/a agarre estrecho concentration curl con barra",
  "0090": "sentado/a good morning con barra",
  "0091": "press militar sentado con barra",
  "0092": "sentado/a overhead extensión de tríceps con barra",
  "0094": "sentado/a con giro con barra",
  "0095": "encogimientos de hombros con barra",
  "0096": "side bent v. 2 con barra",
  "0098": "side split squat con barra",
  "0097": "side split squat v. 2 con barra",
  "0099": "hip thrust con barra",
  "0100": "puente de glúteos con barra",
  "0101": "speed squat con barra",
  "0102": "sentadilla (on knees) con barra",
  "0103": "de pie ab rollerout con barra",
  "0104": "de pie back wrist curl con barra",
  "0105": "de pie bradford press con barra",
  "0106": "de pie agarre estrecho curl con barra",
  "0107": "de pie front raise over head con barra",
  "0108": "de pie leg calf raise con barra",
  "0109": "de pie overhead extensión de tríceps con barra",
  "0110": "de pie agarre supino curl con barra",
  "0111": "de pie rocking leg calf raise con barra",
  "0112": "de pie con giro con barra",
  "0113": "de pie agarre ancho curl con barra",
  "0114": "subidas al cajón (step-ups) con barra",
  "0115": "stiff leg good morning con barra",
  "0116": "piernas rectas deadlift con barra",
  "0117": "peso muerto sumo con barra",
  "0120": "remo al mentón con barra",
  "0119": "remo al mentón v. 2 con barra",
  "0121": "remo al mentón v. 3 con barra",
  "0122": "wide en banco press con barra",
  "0124": "wide squat con barra",
  "0123": "agarre ancho upright row con barra",
  "0126": "curl de muñeca con barra",
  "0125": "curl de muñeca v. 2 con barra",
  "0127": "zercher squat con barra",
  "0128": "battling ropes",
  "0129": "en banco dip (knees bent)",
  "0130": "en banco hip extension",
  "0139": "biceps narrow pull-ups",
  "0140": "biceps pull-up",
  "0137": "body-up",
  "0138": "bottoms-up",
  "0870": "butt-ups",
  "0148": "alterno/a shoulder press en polea",
  "0149": "alterno/a extensión de tríceps en polea",
  "0150": "bar lateral pulldown en polea",
  "0151": "press de banca en polea",
  "0152": "concentration extension (on knee) en polea",
  "0153": "cross-over lateral pulldown en polea",
  "0154": "cross-over revers fly en polea",
  "0155": "cross-over variation en polea",
  "0868": "curl en polea",
  "0157": "peso muerto en polea",
  "0158": "aperturas declinadas en polea",
  "0159": "declinado/a sentado/a agarre ancho row en polea",
  "0160": "floor sentado/a agarre ancho row en polea",
  "0161": "forward raise en polea",
  "0162": "elevaciones frontales en polea",
  "0164": "front shoulder raise en polea",
  "0165": "curl martillo (with rope) en polea",
  "0167": "high row (de rodillas) en polea",
  "0168": "aducción de cadera en polea",
  "0169": "press de banca inclinado en polea",
  "0171": "aperturas inclinadas en polea",
  "0170": "aperturas inclinadas (en fitball) en polea",
  "0172": "inclinado/a pushdown en polea",
  "0173": "inclinado/a extensión de tríceps en polea",
  "0174": "judo flip en polea",
  "0860": "plancha abdominal isométrica",
  "0175": "de rodillas crunch en polea",
  "0176": "de rodillas extensión de tríceps en polea",
  "0177": "lateral pulldown (with rope attachment) en polea",
  "0178": "elevaciones laterales en polea",
  "0179": "low fly en polea",
  "0180": "low sentado/a row en polea",
  "0182": "tumbado/a agarre estrecho curl en polea",
  "0184": "tumbado/a extension pullover (with rope attachment) en polea",
  "0185": "tumbado/a fly en polea",
  "0186": "tumbado/a extensión de tríceps v. 2 en polea",
  "0188": "middle fly en polea",
  "0189": "a una mano remo inclinado en polea",
  "0190": "a una mano curl en polea",
  "0191": "a una mano lateral bent-over en polea",
  "0192": "a una mano lateral raise en polea",
  "0193": "a una mano straight back high row (de rodillas) en polea",
  "0194": "overhead extensión de tríceps (rope attachment) en polea",
  "0195": "curl predicador en polea",
  "0196": "pull-through para glúteos (with rope) en polea",
  "0198": "jalón dorsal en polea",
  "0197": "jalón dorsal (pro lat bar) en polea",
  "0201": "pushdown en polea",
  "0199": "pushdown (straight arm) v. 2 en polea",
  "0200": "pushdown (with rope attachment) en polea",
  "0202": "rear delt row (stirrups) en polea",
  "0203": "rear delt row (with rope) en polea",
  "0204": "rear drive en polea",
  "0205": "rear pulldown en polea",
  "0873": "crunch invertido en polea",
  "0206": "curl invertido en polea",
  "0209": "reverse preacher curl en polea",
  "0210": "curl invertido de muñeca en polea",
  "0207": "reverse-grip pushdown en polea",
  "0208": "reverse-grip straight back sentado/a high row en polea",
  "0211": "giros rusoss (en fitball) en polea",
  "0212": "sentado/a crunch en polea",
  "0213": "sentado/a high row (v-bar) en polea",
  "0214": "sentado/a a una mano alterno/a row en polea",
  "0215": "sentado/a pájaros (deltoides posterior) en polea",
  "0861": "plancha lateral",
  "0216": "sentado/a shoulder internal con rotación en polea",
  "0218": "sentado/a agarre ancho row en polea",
  "0219": "press de hombros en polea",
  "0220": "encogimientos de hombros en polea",
  "0222": "side bend en polea",
  "0221": "side bend crunch (bosu ball) en polea",
  "0223": "side crunch en polea",
  "0224": "de pie back wrist curl en polea",
  "0225": "de pie cross-over high reverse fly en polea",
  "0226": "de pie crunch en polea",
  "0874": "de pie crunch (with rope attachment) en polea",
  "0227": "de pie fly en polea",
  "0228": "de pie hip extension en polea",
  "0229": "de pie inner curl en polea",
  "0230": "de pie lift en polea",
  "0231": "de pie a una mano extensión de tríceps en polea",
  "0232": "de pie pulldown (with rope) en polea",
  "0233": "de pie rear delt row (with rope) en polea",
  "0234": "de pie row (v-bar) en polea",
  "0235": "de pie shoulder external con rotación en polea",
  "0236": "de pie con giro row (v-bar) en polea",
  "0238": "pull-over en polea alta brazos rectos",
  "0237": "pull-over en polea alta brazos rectos (with rope)",
  "0239": "face pull en polea",
  "0240": "jalón al pecho agarre cerrado en polea",
  "0241": "extensión de tríceps en polea alta (barra en V)",
  "0242": "patada de tríceps en polea",
  "0243": "con giro en polea",
  "0862": "escaladores (mountain climbers)",
  "0244": "con giro pull en polea",
  "0245": "curl de bíceps en polea baja",
  "0246": "remo al mentón en polea",
  "0247": "curl de muñeca en polea",
  "0248": "cambered bar tumbado/a row",
  "0251": "fondos de pecho",
  "0253": "dominadas supinass (narrow agarre neutro)",
  "0257": "circles knee estiramiento",
  "0258": "clock push-up",
  "0259": "agarre estrecho push-up",
  "0260": "cocoons",
  "0262": "cross body crunch",
  "0267": "crunch abdominal (hands overhead)",
  "0271": "crunch abdominal (en fitball)",
  "0272": "crunch abdominal (en fitball, arms straight)",
  "0274": "crunch abdominal floor",
  "0276": "bicho muerto (dead bug)",
  "0277": "declinado/a crunch",
  "0279": "declinado/a push-up",
  "0282": "declinado/a sit-up",
  "0283": "diamond push-up",
  "0284": "press de banca con mancuernas",
  "0285": "press inclinado con mancuernas",
  "0286": "press declinado con mancuernas",
  "0287": "press Arnold v. 2 con mancuernas",
  "0288": "around pullover con mancuernas",
  "0289": "press de banca con mancuernas",
  "0290": "en banco sentado/a press con mancuernas",
  "0291": "en banco squat con mancuernas",
  "0293": "remo inclinado con mancuernas",
  "0294": "curl de bíceps con mancuernas",
  "0295": "cargada (clean) con mancuernas",
  "0296": "agarre estrecho press con mancuernas",
  "0297": "curl martillo con mancuernas",
  "0298": "curl concentrado con mancuerna",
  "0299": "cuban press con mancuernas",
  "0300": "peso muerto con mancuernas",
  "0301": "press de banca declinado con mancuernas",
  "0302": "aperturas declinadas con mancuernas",
  "0303": "declinado/a hammer press con mancuernas",
  "0305": "declinado/a shrug con mancuernas",
  "0304": "declinado/a shrug v. 2 con mancuernas",
  "0306": "declinado/a extensión de tríceps con mancuernas",
  "0307": "declinado/a con giro fly con mancuernas",
  "0308": "fly con mancuernas",
  "0310": "aperturas planas con mancuernas",
  "0309": "elevaciones frontales v. 2 con mancuernas",
  "0311": "aperturas inclinadas con mancuernas",
  "0313": "curl martillo con mancuernas",
  "0312": "aperturas declinadas con mancuernas",
  "0314": "press de banca inclinado con mancuernas",
  "0315": "inclinado/a curl de bíceps con mancuernas",
  "0316": "inclinado/a breeding con mancuernas",
  "0318": "curl inclinado de bíceps con mancuernas",
  "0317": "curl inclinado de bíceps v. 2 con mancuernas",
  "0319": "aperturas inclinadas con mancuernas",
  "0320": "inclinado/a hammer curl con mancuernas",
  "0321": "inclinado/a hammer press con mancuernas",
  "0322": "inclinado/a inner curl de bíceps con mancuernas",
  "0323": "inclinado/a a una mano lateral raise con mancuernas",
  "0324": "inclinado/a palm-in press con mancuernas",
  "0325": "inclinado/a raise con mancuernas",
  "0326": "inclinado/a pájaros (deltoides posterior) con mancuernas",
  "0327": "remo inclinado con mancuernas",
  "0328": "inclinado/a shoulder raise con mancuernas",
  "0329": "inclinado/a shrug con mancuernas",
  "0330": "inclinado/a extensión de tríceps con mancuernas",
  "0331": "inclinado/a twisted flyes con mancuernas",
  "0332": "iron cross con mancuernas",
  "0333": "kickback con mancuernas",
  "0334": "elevaciones laterales con mancuernas",
  "0335": "lateral to front raise con mancuernas",
  "0336": "zancadas con mancuernas",
  "0337": "tumbado/a extension (across face) con mancuernas",
  "0338": "tumbado/a elbow press con mancuernas",
  "0863": "burpees",
  "0339": "tumbado/a femoral con mancuernas",
  "0340": "tumbado/a hammer press con mancuernas",
  "0341": "tumbado/a a una mano deltoid rear con mancuernas",
  "0343": "tumbado/a a una mano press con mancuernas",
  "0342": "tumbado/a a una mano press v. 2 con mancuernas",
  "0344": "tumbado/a a una mano pronated extensión de tríceps con mancuernas",
  "0345": "tumbado/a a una mano pájaros (deltoides posterior) con mancuernas",
  "0346": "tumbado/a a una mano supinated extensión de tríceps con mancuernas",
  "0347": "tumbado/a pronation con mancuernas",
  "0348": "pájaros con mancuernas (deltoides posterior)",
  "0349": "tumbado/a supination con mancuernas",
  "0350": "tumbado/a supino curl con mancuernas",
  "0351": "tumbado/a extensión de tríceps con mancuernas",
  "0352": "agarre neutro en banco press con mancuernas",
  "0292": "remo con mancuerna a una mano",
  "0353": "a una mano concentration curl (en fitball) con mancuernas",
  "0354": "a una mano kickback con mancuernas",
  "0355": "a una mano lateral raise con mancuernas",
  "0356": "a una mano lateral raise with support con mancuernas",
  "0358": "a una mano reverse wrist curl con mancuernas",
  "0359": "a una mano reverse fly (with support) con mancuernas",
  "0361": "a una mano shoulder press con mancuernas",
  "0360": "a una mano shoulder press v. 2 con mancuernas",
  "0362": "a una mano extensión de tríceps (en banco) con mancuernas",
  "0363": "a una mano upright row con mancuernas",
  "0364": "a una mano wrist curl con mancuernas",
  "0365": "over en banco neutral wrist curl con mancuernas",
  "0366": "over en banco a una mano neutral wrist curl con mancuernas",
  "0367": "over en banco a una mano wrist curl con mancuernas",
  "0368": "over en banco revers wrist curl con mancuernas",
  "0369": "over en banco wrist curl con mancuernas",
  "0370": "peacher hammer curl con mancuernas",
  "0371": "plyo squat con mancuernas",
  "0372": "curl predicador con mancuernas",
  "0373": "pronate-grip extensión de tríceps con mancuernas",
  "0374": "prono inclinado/a curl con mancuernas",
  "0375": "pull-over con mancuernas",
  "0376": "raise con mancuernas",
  "0377": "rear delt row_shoulder con mancuernas",
  "0378": "press de hombros sentado con mancuernas",
  "0380": "elevaciones frontales con mancuernas",
  "0379": "press Arnold con mancuernas",
  "0381": "remo al mentón con mancuernas",
  "0382": "revers grip curl de bíceps con mancuernas",
  "0383": "pájaros (deltoides posterior) con mancuernas",
  "0384": "reverse preacher curl con mancuernas",
  "0385": "curl invertido de muñeca con mancuernas",
  "0386": "con rotación reverse fly con mancuernas",
  "0387": "sentado/a alterno/a front raise con mancuernas",
  "0388": "sentado/a alterno/a press con mancuernas",
  "0389": "sentado/a en banco extension con mancuernas",
  "0390": "sentado/a curl de bíceps (en fitball) con mancuernas",
  "0391": "sentado/a curl con mancuernas",
  "0392": "sentado/a front raise con mancuernas",
  "0393": "sentado/a inner curl de bíceps con mancuernas",
  "0394": "sentado/a kickback con mancuernas",
  "0396": "sentado/a lateral raise con mancuernas",
  "0395": "sentado/a lateral raise v. 2 con mancuernas",
  "0397": "sentado/a neutral wrist curl con mancuernas",
  "0398": "sentado/a a una mano kickback con mancuernas",
  "0399": "encogimientos de hombros con mancuernas",
  "0400": "sentado/a a una pierna calf raise con mancuernas",
  "0401": "sentadilla goblet con mancuerna",
  "0402": "sentadilla búlgara con mancuernas",
  "0403": "peso muerto rumano con mancuernas",
  "0405": "sentado/a shoulder press con mancuernas",
  "0404": "sentado/a shoulder press (agarre neutro) con mancuernas",
  "0406": "encogimientos de hombros con mancuernas",
  "0407": "side bend con mancuernas",
  "0408": "side tumbado/a one hand raise con mancuernas",
  "0409": "a una pierna calf raise con mancuernas",
  "0410": "a una pierna split squat con mancuernas",
  "0411": "a una pierna squat con mancuernas",
  "0413": "sentadilla con mancuernas",
  "0414": "de pie alterno/a overhead press con mancuernas",
  "0415": "de pie alterno/a raise con mancuernas",
  "0416": "de pie curl de bíceps con mancuernas",
  "0417": "elevación de talones de pie con mancuernas",
  "0418": "de pie concentration curl con mancuernas",
  "0419": "de pie front raise above head con mancuernas",
  "0420": "de pie kickback con mancuernas",
  "0421": "de pie a una mano concentration curl con mancuernas",
  "0422": "de pie a una mano curl (over inclinado/a en banco) con mancuernas",
  "0423": "de pie a una mano extension con mancuernas",
  "0424": "de pie a una mano palm in press con mancuernas",
  "0425": "de pie a una mano reverse curl con mancuernas",
  "0426": "de pie overhead press con mancuernas",
  "0427": "de pie palms in press con mancuernas",
  "0428": "de pie preacher curl con mancuernas",
  "0429": "de pie reverse curl con mancuernas",
  "0430": "de pie extensión de tríceps con mancuernas",
  "0431": "subidas al cajón (step-ups) con mancuernas",
  "0432": "peso muerto piernas rígidas con mancuernas",
  "0433": "straight arm pullover con mancuernas",
  "0434": "piernas rectas deadlift con mancuernas",
  "0436": "press Tate con mancuernas",
  "0437": "remo al mentón con mancuernas",
  "0864": "fondos en paralelas para pecho",
  "0438": "w-press con mancuernas",
  "0439": "zottman curl con mancuernas",
  "0443": "elbow-to-knee",
  "0445": "anti gravity press con barra EZ",
  "0446": "sentadilla hack con barra",
  "0447": "curl con barra EZ",
  "0448": "declinado/a agarre estrecho face press con barra EZ",
  "0449": "inclinado/a extensión de tríceps con barra EZ",
  "0450": "jm en banco press con barra EZ",
  "0451": "agarre supino curl con barra EZ",
  "0452": "agarre supino preacher curl con barra EZ",
  "0453": "sentado/a extensión de tríceps con barra EZ",
  "0454": "curl araña con barra EZ",
  "0455": "finger curls",
  "0456": "flexion leg sit up (rodillas flexionadas)",
  "0457": "flexion leg sit up (straight arm)",
  "0458": "floor fly (with barbell) con barra",
  "0459": "aleteo de piernas (flutter kicks)",
  "0464": "front plank with con giro",
  "0466": "gironda sternum chin",
  "0467": "gorilla chin",
  "0469": "groin crunch",
  "0471": "handstand push-up",
  "0472": "elevación de piernas colgado",
  "0473": "colgado/a pike",
  "0474": "colgado/a piernas rectas hip raise",
  "0475": "colgado/a piernas rectas raise",
  "0476": "colgado/a straight con giro leg hip raise",
  "0484": "hip raise (rodillas flexionadas)",
  "0489": "hiperextensiones lumbares",
  "0488": "hiperextensiones lumbares (en banco)",
  "0490": "inclinado/a agarre estrecho push-up",
  "0491": "inclinado/a leg hip raise (leg straight)",
  "0492": "inclinado/a push up depth jump",
  "0493": "inclinado/a push-up",
  "0494": "inclinado/a agarre supino push-up",
  "0495": "inclinado/a con giro sit-up",
  "0496": "inverse leg curl (en banco support)",
  "0499": "remo invertido (australiano)",
  "0497": "remo invertido (australiano) v. 2",
  "0498": "remo invertido (australiano) with straps",
  "0500": "isometric wipers",
  "0501": "jack burpee",
  "0507": "jackknife sit-up",
  "0508": "janda sit-up",
  "0514": "jump squat",
  "0513": "jump squat v. 2",
  "0517": "advanced windmill con pesa rusa",
  "0518": "alterno/a hang clean con pesa rusa",
  "0520": "alterno/a press con pesa rusa",
  "0519": "alterno/a press en suelo con pesa rusa",
  "0521": "alterno/a renegade row con pesa rusa",
  "0522": "alterno/a row con pesa rusa",
  "0523": "press Arnold con pesa rusa",
  "0524": "bent press con pesa rusa",
  "0525": "bottoms up clean from the hang position con pesa rusa",
  "0526": "double alterno/a hang clean con pesa rusa",
  "0527": "double jerk con pesa rusa",
  "0528": "sentadilla hack en máquina",
  "0529": "double snatch con pesa rusa",
  "0530": "double windmill con pesa rusa",
  "0531": "extended range a una mano press en suelo con pesa rusa",
  "0532": "figure 8 con pesa rusa",
  "0533": "sentadilla frontal con pesa rusa",
  "0534": "sentadilla goblet con pesa rusa",
  "0535": "hang clean con pesa rusa",
  "0536": "zancadas pass through con pesa rusa",
  "0537": "a una mano clean and jerk con pesa rusa",
  "0538": "a una mano jerk con pesa rusa",
  "0539": "a una mano military press to the side con pesa rusa",
  "0540": "a una mano push press con pesa rusa",
  "0541": "remo a una mano con pesa rusa",
  "0542": "a una mano snatch con pesa rusa",
  "0543": "pirate supper legs con pesa rusa",
  "0544": "sentadilla a una pierna (pistol) con pesa rusa",
  "0545": "plyo push-up con pesa rusa",
  "0546": "sentado/a press con pesa rusa",
  "0547": "seesaw press con pesa rusa",
  "0548": "sumo high pull con pesa rusa",
  "0549": "swing con pesa rusa",
  "0550": "thruster con pesa rusa",
  "0551": "turkish get up (squat style) con pesa rusa",
  "0552": "two arm clean con pesa rusa",
  "0553": "two arm military press con pesa rusa",
  "0554": "windmill con pesa rusa",
  "0555": "kick out sit",
  "0558": "kipping muscle up",
  "0562": "landmine 180",
  "0570": "leg pull in flat en banco",
  "0571": "alterno/a narrow grip sentado/a row en máquina",
  "0572": "assisted chin-up en máquina",
  "0573": "hiperextensiones lumbares en máquina",
  "0574": "remo inclinado en máquina",
  "0575": "curl de bíceps en máquina",
  "0577": "press de pecho en máquina",
  "0576": "press de pecho en máquina",
  "0578": "peso muerto en máquina",
  "0579": "front pulldown en máquina",
  "0580": "gripless shrug en máquina",
  "0581": "high row en máquina",
  "0582": "de rodillas leg curl en máquina",
  "0583": "de rodillas con giro en máquina",
  "0584": "elevaciones laterales en máquina",
  "0585": "extensiones de cuádriceps en máquina",
  "0586": "curl femoral tumbado en máquina",
  "0587": "press militar en máquina",
  "0588": "narrow grip sentado/a row en máquina",
  "0589": "a una mano remo inclinado en máquina",
  "0590": "a una mano shoulder press en máquina",
  "0591": "agarre prono fondos de tríceps en máquina",
  "0592": "curl predicador en máquina",
  "0593": "reverse hiperextensiones lumbares en máquina",
  "0594": "elevación de talones sentado en máquina",
  "0595": "sentado/a crunch (chest pad) en máquina",
  "0596": "sentado/a fly en máquina",
  "0597": "sentado/a hip abduction en máquina",
  "0598": "sentado/a hip adduction en máquina",
  "0599": "curl femoral sentado en máquina",
  "0600": "sentado/a leg raise crunch en máquina",
  "0602": "sentado/a reverse fly en máquina",
  "0601": "sentado/a reverse fly (agarre neutro) en máquina",
  "0603": "press de hombros en máquina",
  "0869": "press de hombros v. 2 en máquina",
  "0604": "encogimientos de hombros en máquina",
  "0605": "elevación de talones de pie en máquina",
  "0606": "remo en barra T en máquina",
  "0607": "extensión de tríceps en máquina",
  "0609": "london bridge",
  "0613": "tumbado/a (side) quads estiramiento",
  "0620": "elevación de piernas tumbado flat en banco",
  "0865": "tumbado/a leg-hip raise",
  "0624": "march sit (wall)",
  "0627": "mixed grip chin-up",
  "0628": "monster walk",
  "0630": "escaladores (mountain climbers)",
  "0631": "muscle up",
  "0634": "negative crunch",
  "0635": "oblique crunches floor",
  "0636": "olympic barbell hammer curl",
  "0637": "olympic barbell extensión de tríceps",
  "0638": "a una mano chin-up",
  "0639": "aperturas en contractora de pecho (pec deck)",
  "0640": "pájaros en contractora inversa (deltoides posterior)",
  "0641": "otis up",
  "0642": "outside leg kick push-up",
  "0643": "overhead triceps estiramiento",
  "0648": "power clean",
  "0651": "dominadas (agarre neutro)",
  "0650": "pull-in (en fitball)",
  "0652": "dominadas",
  "0662": "flexiones de brazos",
  "0653": "flexiones de brazos (bosu ball) en bosu",
  "0655": "remo sentado en polea baja",
  "0656": "jalón al pecho trasnuca en polea",
  "0659": "flexiones de brazos (wall)",
  "0658": "fondos en máquina",
  "0660": "flexiones de brazos agarre estrecho off dumbbell",
  "0661": "flexiones de brazos inside leg kick",
  "0663": "flexiones de brazos medicine ball con balón medicinal",
  "0664": "flexiones de brazos to side plank",
  "0666": "raise a una mano push-up",
  "0668": "rear declinado/a bridge",
  "0669": "rear deltoid estiramiento",
  "0670": "rear pull-up",
  "0872": "crunch invertido",
  "0672": "reverse dip",
  "0673": "agarre supino machine lat pulldown",
  "0674": "agarre supino pull-up",
  "0675": "curl de bíceps en máquina",
  "0677": "ring dips",
  "0678": "rocky pull-up pulldown",
  "0680": "rope climb",
  "0685": "run",
  "0684": "run (equipment)",
  "0687": "giros rusos",
  "0688": "scapular pull-up",
  "0689": "sentado/a leg raise",
  "0690": "sentado/a lower back estiramiento",
  "0691": "sentado/a side crunch (wall)",
  "0697": "self assisted inverse leg curl",
  "0696": "self assisted inverse leg curl (en suelo)",
  "0699": "shoulder tap push-up",
  "0705": "side bridge v. 2",
  "0709": "side hip (on parallel bars)",
  "0710": "side hip abduction",
  "0716": "side push neck estiramiento",
  "0717": "side push-up",
  "0721": "side wrist pull estiramiento",
  "0720": "side-to-side chin",
  "0725": "a una mano push-up",
  "0727": "a una pierna calf raise (on a dumbbell)",
  "0730": "a una pierna platform slide",
  "0735": "abdominales sit-up v. 2",
  "0738": "sled 45в° calf press",
  "0739": "prensa de piernas inclinada",
  "0740": "aducción de cadera en máquina",
  "0741": "abducción de cadera en máquina",
  "0742": "sled forward angled calf raise",
  "0743": "sled hack squat",
  "0744": "sled tumbado/a squat",
  "0746": "back shrug en máquina Smith",
  "0747": "trasnuca press en máquina Smith",
  "0748": "press de banca en máquina Smith",
  "0749": "rodillas flexionadas good morning en máquina Smith",
  "0750": "chair squat en máquina Smith",
  "0751": "press de banca agarre cerrado en máquina Smith",
  "0752": "peso muerto en máquina Smith",
  "0753": "press de banca declinado en máquina Smith",
  "0754": "declinado/a reverse-grip press en máquina Smith",
  "0755": "sentadilla hack en máquina Smith",
  "0756": "hip raise en máquina Smith",
  "0757": "press de banca inclinado en máquina Smith",
  "0758": "inclinado/a reverse-grip press en máquina Smith",
  "0759": "inclinado/a shoulder raises en máquina Smith",
  "0760": "prensa de piernas en máquina Smith",
  "0761": "narrow row en máquina Smith",
  "0762": "rear delt row en máquina Smith",
  "0763": "reverse calf raises en máquina Smith",
  "0764": "reverse-grip press en máquina Smith",
  "0765": "sentado/a shoulder press en máquina Smith",
  "0766": "press de hombros en máquina Smith",
  "0767": "encogimientos de hombros en máquina Smith",
  "0768": "a una pierna split squat en máquina Smith",
  "0769": "sprint lunge en máquina Smith",
  "0770": "sentadilla en máquina Smith",
  "0771": "de pie back wrist curl en máquina Smith",
  "0772": "de pie behind head military press en máquina Smith",
  "0773": "de pie leg calf raise en máquina Smith",
  "0774": "de pie military press en máquina Smith",
  "0775": "remo al mentón en máquina Smith",
  "0776": "arrancada (snatch) pull",
  "0777": "spell caster",
  "0778": "spider crawl push up",
  "0786": "sentadilla jerk",
  "0788": "de pie trasnuca press",
  "0794": "de pie lateral estiramiento",
  "0795": "de pie a una pierna curl",
  "0796": "de pie wheel rollerout",
  "0798": "stationary bike walk",
  "0803": "superman push-up",
  "0805": "abdominal fallout en suspensión (TRX)",
  "0806": "flexiones de brazos en suspensión (TRX)",
  "0807": "crunch invertido en suspensión (TRX)",
  "0808": "remo en suspensión (TRX)",
  "0809": "sentadilla dividida en suspensión (TRX)",
  "0811": "peso muerto con barra hexagonal",
  "0814": "press de banca en máquina Smith",
  "0812": "fondos de tríceps (en banco leg)",
  "0813": "fondos de tríceps (between benches)",
  "0815": "press inclinado en máquina Smith",
  "0816": "sentadilla en máquina Smith",
  "0817": "triceps estiramiento",
  "0871": "tuck crunch",
  "0818": "twin handle agarre neutro lat pulldown",
  "0826": "vertical leg raise (on parallel bars)",
  "0830": "en banco dip con lastre",
  "0832": "crunch abdominal con lastre",
  "0833": "elevación de talones en burro con lastre",
  "0834": "elevaciones frontales con lastre",
  "0866": "colgado/a leg-hip raise con lastre",
  "0835": "hiperextensiones lumbares (en fitball)",
  "0840": "overhead crunch (en fitball)",
  "0841": "dominadas con lastre",
  "0844": "round arm con lastre",
  "0846": "giros rusos con lastre",
  "0845": "giros rusos (legs up) con lastre",
  "0847": "sentado/a bicep curl (en fitball)",
  "0849": "sentado/a con giro (en fitball)",
  "0850": "side bend (en fitball)",
  "0851": "sentadilla sissy con lastre",
  "0852": "sentadilla con lastre",
  "0853": "de pie curl con lastre",
  "0854": "de pie hand squeeze con lastre",
  "0856": "press Svend con lastre",
  "0857": "rollerout",
  "0858": "wind sprints",
  "0859": "wrist rollerer"
}
